import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

/**
 * SOLO Estate - Complete Real Projects Seed
 * All data sourced from korter.ge
 * All 82 active projects from 16 Georgian developers
 *
 * Note: Only active projects included (SOLD OUT projects excluded)
 * Investment metrics and images to be added separately
 */

interface ProjectData {
  slug: string
  titleEn: string
  titleKa: string
  titleRu: string
  descriptionEn: string
  descriptionKa: string
  descriptionRu: string
  developerSlug: string
  locationCity: string
  locationArea?: string
  locationAddress?: string
  price: number
  pricePerSqm?: number | null
  priceFrom?: number | null
  propertyType: 'apartment' | 'aparthotel' | 'villa'
  status: 'offPlan' | 'underConstruction' | 'ready'
  deliveryQuarter?: string | null
  deliveryYear?: number | null
  featured: boolean
}

// Helper function to create default descriptions for different languages
const createDesc = (base: string, city: string): { ka: string; ru: string } => ({
  ka: `${base} ${city === 'Tbilisi' ? 'თბილისში' : city === 'Batumi' ? 'ბათუმში' : city + '-ში'}.`,
  ru: `${base} в ${city === 'Tbilisi' ? 'Тбилиси' : city === 'Batumi' ? 'Батуми' : city}.`
})

const projectsData: ProjectData[] = [
  // ========================================
  // VR HOLDING - 5 Projects
  // ========================================
  {
    slug: 'krtsanisi-resort-residence',
    titleEn: 'Krtsanisi Resort Residence',
    titleKa: 'კრწანისის რეზორტ რეზიდენცია',
    titleRu: 'Крцаниси Резорт Резиденс',
    descriptionEn: 'First resort-type settlement in the diplomatic district. Luxury residential complex combining modern amenities with natural surroundings.',
    descriptionKa: 'პირველი რეზორტული ტიპის დასახლება დიპლომატიურ რაიონში.',
    descriptionRu: 'Первый поселок курортного типа в дипломатическом районе.',
    developerSlug: 'vr-holding',
    locationCity: 'Tbilisi',
    locationArea: 'Krtsanisi',
    price: 195500,
    pricePerSqm: 1955,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2028,
    featured: false,
  },
  {
    slug: 'vr-shekvetili-forest-beach',
    titleEn: 'VR Shekvetili Forest-Beach',
    titleKa: 'VR შექვეთილი ფორესტ-ბიჩი',
    titleRu: 'VR Шекветили Форест-Бич',
    descriptionEn: 'New destination on the Black Sea coast, designed for active living in all four seasons.',
    descriptionKa: 'ახალი დანიშნულება შავი ზღვის სანაპიროზე.',
    descriptionRu: 'Новое направление на побережье Черного моря.',
    developerSlug: 'vr-holding',
    locationCity: 'Shekvetili',
    price: 150000,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2028,
    featured: false,
  },
  {
    slug: 'vr-townhouse-apartments',
    titleEn: 'VR Townhouse Apartments',
    titleKa: 'VR თაუნჰაუს აპარტამენტები',
    titleRu: 'VR Таунхаус Апартаменты',
    descriptionEn: 'Modern townhouse apartments in prestigious Krtsanisi district.',
    descriptionKa: 'თანამედროვე თაუნჰაუსები პრესტიჟულ კრწანისში.',
    descriptionRu: 'Современные таунхаусы в престижном Крцаниси.',
    developerSlug: 'vr-holding',
    locationCity: 'Tbilisi',
    locationArea: 'Krtsanisi',
    price: 105000,
    pricePerSqm: 2100,
    propertyType: 'villa',
    status: 'underConstruction',
    deliveryQuarter: 'Q1',
    deliveryYear: 2026,
    featured: false,
  },
  {
    slug: 'tsavkisi-villa-residence',
    titleEn: 'Tsavkisi Villa Residence',
    titleKa: 'წავკისის ვილა რეზიდენცია',
    titleRu: 'Цавкиси Вилла Резиденс',
    descriptionEn: 'Exclusive villa residence in Tsavkisi. Luxurious mountain living.',
    descriptionKa: 'ექსკლუზიური ვილა რეზიდენცია წავკისში.',
    descriptionRu: 'Эксклюзивная вилла резиденция в Цавкиси.',
    developerSlug: 'vr-holding',
    locationCity: 'Tsavkisi',
    price: 200000,
    propertyType: 'villa',
    status: 'underConstruction',
    featured: false,
  },
  {
    slug: 'vr-vake-sky-tower',
    titleEn: 'VR Vake Sky Tower',
    titleKa: 'VR ვაკე სკაი თაუერი',
    titleRu: 'VR Ваке Скай Тауэр',
    descriptionEn: 'Will be the tallest building in Tbilisi at 180 meters. Premium high-rise in Vake.',
    descriptionKa: 'იქნება თბილისის უმაღლესი შენობა 180 მეტრით.',
    descriptionRu: 'Будет самым высоким зданием в Тбилиси.',
    developerSlug: 'vr-holding',
    locationCity: 'Tbilisi',
    locationArea: 'Vake',
    locationAddress: '49 Chavchavadze Street',
    price: 250000,
    propertyType: 'apartment',
    status: 'offPlan',
    deliveryQuarter: 'Q3',
    deliveryYear: 2028,
    featured: true,
  },

  // ========================================
  // BIOGRAPI LIVING - 7 Projects
  // ========================================
  {
    slug: 'hisni-by-biograpi',
    titleEn: 'Hisni',
    titleKa: 'ჰისნი',
    titleRu: 'Хисни',
    descriptionEn: 'Premium residential complex in Isani district.',
    descriptionKa: 'პრემიუმ საცხოვრებელი კომპლექსი ისანში.',
    descriptionRu: 'Премиум жилой комплекс в Исани.',
    developerSlug: 'biograpi',
    locationCity: 'Tbilisi',
    locationArea: 'Isani',
    locationAddress: 'Ketevan Dedofali Ave, 69',
    price: 150000,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2028,
    featured: false,
  },
  {
    slug: 'sakeni-by-biograpi',
    titleEn: 'Sakeni',
    titleKa: 'საკენი',
    titleRu: 'Сакени',
    descriptionEn: 'Premium apartment complex in Saburtalo on Vaja-Pshavela Avenue.',
    descriptionKa: 'პრემიუმ აპარტამენტების კომპლექსი საბურთალოში.',
    descriptionRu: 'Премиум комплекс в Сабуртало.',
    developerSlug: 'biograpi',
    locationCity: 'Tbilisi',
    locationArea: 'Saburtalo',
    locationAddress: 'Vaja-Pshavela Ave, 25',
    price: 124402,
    pricePerSqm: 2925,
    priceFrom: 124402,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2026,
    featured: true,
  },
  {
    slug: 'bare-by-biograpi',
    titleEn: 'Bare by Biograpi',
    titleKa: 'ბარე ბიოგრაფი',
    titleRu: 'Баре от Биографи',
    descriptionEn: 'Premium residential project in Isani with exceptional design.',
    descriptionKa: 'პრემიუმ საცხოვრებელი პროექტი ისანში.',
    descriptionRu: 'Премиальный жилой проект в Исани.',
    developerSlug: 'biograpi',
    locationCity: 'Tbilisi',
    locationArea: 'Isani',
    locationAddress: 'Niko Lomouri St. 3',
    price: 116600,
    pricePerSqm: 3800,
    priceFrom: 116600,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2027,
    featured: false,
  },
  {
    slug: 'matiani-by-biograpi',
    titleEn: 'Matiani',
    titleKa: 'მატიანი',
    titleRu: 'Матиани',
    descriptionEn: 'Premium residential complex in Didube on Akaki Tsereteli Avenue.',
    descriptionKa: 'პრემიუმ საცხოვრებელი კომპლექსი დიდუბეში.',
    descriptionRu: 'Премиум жилой комплекс в Дидубе.',
    developerSlug: 'biograpi',
    locationCity: 'Tbilisi',
    locationArea: 'Didube',
    locationAddress: 'Akaki Tsereteli Ave, 45',
    price: 70606,
    pricePerSqm: 1700,
    priceFrom: 70606,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2026,
    featured: false,
  },
  {
    slug: 'daira-by-biograpi',
    titleEn: 'Daira by Biograpi',
    titleKa: 'დაირა ბიოგრაფი',
    titleRu: 'Даира от Биографи',
    descriptionEn: 'Premium apartments in Krtsanisi diplomatic district.',
    descriptionKa: 'პრემიუმ აპარტამენტები კრწანისში.',
    descriptionRu: 'Премиум апартаменты в Крцаниси.',
    developerSlug: 'biograpi',
    locationCity: 'Tbilisi',
    locationArea: 'Krtsanisi',
    locationAddress: 'Vakhtang Gorgasali St. 73',
    price: 75038,
    pricePerSqm: 1875,
    priceFrom: 75038,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q1',
    deliveryYear: 2029,
    featured: false,
  },
  {
    slug: 'chantan-by-biograpi',
    titleEn: 'Chantan by Biograpi',
    titleKa: 'ჭანტანი ბიოგრაფი',
    titleRu: 'Чантан от Биографи',
    descriptionEn: 'Premium residential development in Didube.',
    descriptionKa: 'პრემიუმ საცხოვრებელი განვითარება დიდუბეში.',
    descriptionRu: 'Премиум жилой комплекс в Дидубе.',
    developerSlug: 'biograpi',
    locationCity: 'Tbilisi',
    locationArea: 'Didube',
    locationAddress: 'Vladimer Maiakovski St, 9',
    price: 67494,
    pricePerSqm: 1700,
    priceFrom: 67494,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q2',
    deliveryYear: 2027,
    featured: false,
  },
  {
    slug: 'libretto-by-biograpi',
    titleEn: 'Libretto by Biograpi',
    titleKa: 'ლიბრეტო ბიოგრაფი',
    titleRu: 'Либретто от Биографи',
    descriptionEn: 'Upcoming project in premium Vake location.',
    descriptionKa: 'მომავალი პროექტი პრემიუმ ვაკეში.',
    descriptionRu: 'Предстоящий проект в премиальной Ваке.',
    developerSlug: 'biograpi',
    locationCity: 'Tbilisi',
    locationArea: 'Vake',
    locationAddress: 'Zakaria Paliashvili St, 11b',
    price: 120000,
    propertyType: 'apartment',
    status: 'offPlan',
    featured: false,
  },

  // ========================================
  // MONOLITH GROUP - 3 Projects
  // ========================================
  {
    slug: 'monolith-ethno-city',
    titleEn: 'Monolith Ethno City',
    titleKa: 'მონოლითი ეთნო სითი',
    titleRu: 'Монолит Этно Сити',
    descriptionEn: 'Modern residential complex in Krtsanisi near Nadirvari Street.',
    descriptionKa: 'თანამედროვე საცხოვრებელი კომპლექსი კრწანისში.',
    descriptionRu: 'Современный жилой комплекс в Крцаниси.',
    developerSlug: 'monolith-group',
    locationCity: 'Tbilisi',
    locationArea: 'Krtsanisi',
    price: 70000,
    pricePerSqm: 1400,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2026,
    featured: false,
  },
  {
    slug: 'monolith-green-city',
    titleEn: 'Monolith Green City',
    titleKa: 'მონოლითი გრინ სითი',
    titleRu: 'Монолит Грин Сити',
    descriptionEn: 'Ready residential complex in Krtsanisi. Move-in ready apartments.',
    descriptionKa: 'მზად საცხოვრებელი კომპლექსი კრწანისში.',
    descriptionRu: 'Готовый жилой комплекс в Крцаниси.',
    developerSlug: 'monolith-group',
    locationCity: 'Tbilisi',
    locationArea: 'Krtsanisi',
    locationAddress: 'Nadikvari III Street',
    price: 60000,
    pricePerSqm: 1200,
    propertyType: 'apartment',
    status: 'ready',
    deliveryYear: 2025,
    featured: false,
  },
  {
    slug: 'monolith-dighomi-city',
    titleEn: 'Monolith Dighomi City',
    titleKa: 'მონოლითი დიღომი სითი',
    titleRu: 'Монолит Дигоми Сити',
    descriptionEn: 'Residential complex in Saburtalo with modern amenities.',
    descriptionKa: 'საცხოვრებელი კომპლექსი საბურთალოში.',
    descriptionRu: 'Жилой комплекс в Сабуртало.',
    developerSlug: 'monolith-group',
    locationCity: 'Tbilisi',
    locationArea: 'Saburtalo',
    locationAddress: 'Bob Walsh 1 Turn',
    price: 55500,
    pricePerSqm: 1110,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q2',
    deliveryYear: 2027,
    featured: false,
  },

  // ========================================
  // NEXT GROUP - 8 Projects
  // ========================================
  {
    slug: 'next-downtown-batumi',
    titleEn: 'Next Downtown',
    titleKa: 'ნექსთ დაუნთაუნი',
    titleRu: 'Некст Даунтаун',
    descriptionEn: 'Premium residential complex in Batumi Old City. Highest price per m².',
    descriptionKa: 'პრემიუმ საცხოვრებელი კომპლექსი ბათუმის ძველ ქალაქში.',
    descriptionRu: 'Премиум жилой комплекс в Старом городе Батуми.',
    developerSlug: 'next-group',
    locationCity: 'Batumi',
    locationArea: 'Old City',
    price: 200000,
    pricePerSqm: 4050,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2025,
    featured: true,
  },
  {
    slug: 'wyndham-residence-batumi',
    titleEn: 'Wyndham Residence Batumi',
    titleKa: 'ვინდჰემ რეზიდენს ბათუმი',
    titleRu: 'Виндхэм Резиденс Батуми',
    descriptionEn: 'Branded hotel residence in Gonio under Wyndham Hotels brand.',
    descriptionKa: 'ბრენდირებული სასტუმრო რეზიდენცია გონიოში.',
    descriptionRu: 'Брендированная отельная резиденция в Гонио.',
    developerSlug: 'next-group',
    locationCity: 'Gonio',
    price: 138600,
    pricePerSqm: 2772,
    propertyType: 'aparthotel',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2026,
    featured: true,
  },
  {
    slug: 'tbilisi-downtown-next',
    titleEn: 'Tbilisi Downtown',
    titleKa: 'თბილისი დაუნთაუნი',
    titleRu: 'Тбилиси Даунтаун',
    descriptionEn: 'Modern residential complex in Isani district.',
    descriptionKa: 'თანამედროვე საცხოვრებელი კომპლექსი ისანში.',
    descriptionRu: 'Современный жилой комплекс в Исани.',
    developerSlug: 'next-group',
    locationCity: 'Tbilisi',
    locationArea: 'Isani',
    price: 112500,
    pricePerSqm: 2250,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q3',
    deliveryYear: 2027,
    featured: false,
  },
  {
    slug: 'radisson-residences-gonio',
    titleEn: 'Radisson Residences',
    titleKa: 'რედისონ რეზიდენსები',
    titleRu: 'Рэдиссон Резиденс',
    descriptionEn: 'Branded hotel residence in Gonio under Radisson Hotels brand.',
    descriptionKa: 'ბრენდირებული სასტუმრო რეზიდენცია გონიოში.',
    descriptionRu: 'Брендированная отельная резиденция в Гонио.',
    developerSlug: 'next-group',
    locationCity: 'Gonio',
    price: 158000,
    pricePerSqm: 3160,
    propertyType: 'aparthotel',
    status: 'underConstruction',
    deliveryQuarter: 'Q2',
    deliveryYear: 2027,
    featured: true,
  },
  {
    slug: 'next-address-batumi',
    titleEn: 'Next Address',
    titleKa: 'ნექსთ ადრესი',
    titleRu: 'Некст Адрес',
    descriptionEn: 'Residential development in Batumi Khimshiashvili area.',
    descriptionKa: 'საცხოვრებელი განვითარება ბათუმში.',
    descriptionRu: 'Жилой комплекс в Батуми.',
    developerSlug: 'next-group',
    locationCity: 'Batumi',
    locationArea: 'Khimshiashvili',
    price: 90500,
    pricePerSqm: 1810,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2027,
    featured: false,
  },
  {
    slug: 'next-collection-makhinjauri',
    titleEn: 'Next Collection',
    titleKa: 'ნექსთ კოლექშენი',
    titleRu: 'Некст Коллекшн',
    descriptionEn: 'Premium residential collection in Makhinjauri.',
    descriptionKa: 'პრემიუმ საცხოვრებელი კოლექცია მახინჯაურში.',
    descriptionRu: 'Премиум жилая коллекция в Махинджаури.',
    developerSlug: 'next-group',
    locationCity: 'Makhinjauri',
    price: 95000,
    pricePerSqm: 1900,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q2',
    deliveryYear: 2026,
    featured: false,
  },
  {
    slug: 'tbilisi-oriental-by-next',
    titleEn: 'Tbilisi Oriental By Next',
    titleKa: 'თბილისი ორიენტალ ბაი ნექსთ',
    titleRu: 'Тбилиси Ориентал от Некст',
    descriptionEn: 'Upcoming residential project in Krtsanisi.',
    descriptionKa: 'მომავალი საცხოვრებელი პროექტი კრწანისში.',
    descriptionRu: 'Предстоящий жилой проект в Крцаниси.',
    developerSlug: 'next-group',
    locationCity: 'Tbilisi',
    locationArea: 'Krtsanisi',
    price: 130000,
    propertyType: 'apartment',
    status: 'offPlan',
    deliveryQuarter: 'Q4',
    deliveryYear: 2028,
    featured: false,
  },
  {
    slug: 'next-gardens-gonio',
    titleEn: 'Next Gardens',
    titleKa: 'ნექსთ გარდენსი',
    titleRu: 'Некст Гарденс',
    descriptionEn: 'Garden-style residential complex in Gonio.',
    descriptionKa: 'ბაღის სტილის საცხოვრებელი კომპლექსი გონიოში.',
    descriptionRu: 'Жилой комплекс в садовом стиле в Гонио.',
    developerSlug: 'next-group',
    locationCity: 'Gonio',
    price: 87500,
    pricePerSqm: 1750,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2027,
    featured: false,
  },

  // ========================================
  // INDEX I WEALTH MANAGEMENT - 7 Projects
  // ========================================
  {
    slug: 'bochorma-by-index',
    titleEn: 'Bochorma by Index',
    titleKa: 'ბოჩორმა ბაი ინდექსი',
    titleRu: 'Бочорма от Индекс',
    descriptionEn: 'Residential complex in Isani on Bochorma Street.',
    descriptionKa: 'საცხოვრებელი კომპლექსი ისანში.',
    descriptionRu: 'Жилой комплекс в Исани.',
    developerSlug: 'index-wealth-management',
    locationCity: 'Tbilisi',
    locationArea: 'Isani',
    locationAddress: 'Bochorma St, 23',
    price: 80000,
    pricePerSqm: 1600,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2027,
    featured: false,
  },
  {
    slug: 'avlabari-by-index',
    titleEn: 'Avlabari by Index',
    titleKa: 'ავლაბარი ბაი ინდექსი',
    titleRu: 'Авлабари от Индекс',
    descriptionEn: 'Modern apartments in Isani on Telavi Street.',
    descriptionKa: 'თანამედროვე აპარტამენტები ისანში.',
    descriptionRu: 'Современные апартаменты в Исани.',
    developerSlug: 'index-wealth-management',
    locationCity: 'Tbilisi',
    locationArea: 'Isani',
    locationAddress: 'Telavi Street',
    price: 85000,
    pricePerSqm: 1700,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2027,
    featured: false,
  },
  {
    slug: 'gldani-by-index',
    titleEn: 'Gldani by Index',
    titleKa: 'გლდანი ბაი ინდექსი',
    titleRu: 'Глдани от Индекс',
    descriptionEn: 'Budget-friendly residential complex in Gldani.',
    descriptionKa: 'ბიუჯეტური საცხოვრებელი კომპლექსი გლდანში.',
    descriptionRu: 'Бюджетный жилой комплекс в Глдани.',
    developerSlug: 'index-wealth-management',
    locationCity: 'Tbilisi',
    locationArea: 'Gldani',
    locationAddress: 'Ramaz Shengelia St',
    price: 45000,
    pricePerSqm: 900,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2026,
    featured: false,
  },
  {
    slug: 'niabi-by-index',
    titleEn: 'Niabi by Index',
    titleKa: 'ნიაბი ბაი ინდექსი',
    titleRu: 'Ниаби от Индекс',
    descriptionEn: 'Residential development in Isani on Niabi Street.',
    descriptionKa: 'საცხოვრებელი განვითარება ისანში.',
    descriptionRu: 'Жилой комплекс в Исани.',
    developerSlug: 'index-wealth-management',
    locationCity: 'Tbilisi',
    locationArea: 'Isani',
    locationAddress: 'Niabi St, 4',
    price: 74000,
    pricePerSqm: 1480,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q2',
    deliveryYear: 2026,
    featured: false,
  },
  {
    slug: 'river-park-by-index',
    titleEn: 'River Park by Index',
    titleKa: 'რივერ პარკი ბაი ინდექსი',
    titleRu: 'Ривер Парк от Индекс',
    descriptionEn: 'Riverside residential complex in Saburtalo.',
    descriptionKa: 'მდინარის პარკი საბურთალოში.',
    descriptionRu: 'Парк у реки в Сабуртало.',
    developerSlug: 'index-wealth-management',
    locationCity: 'Tbilisi',
    locationArea: 'Saburtalo',
    locationAddress: 'Lasha Lashkhia Street',
    price: 62500,
    pricePerSqm: 1250,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2026,
    featured: false,
  },
  {
    slug: 'isani-by-index',
    titleEn: 'Isani by Index',
    titleKa: 'ისანი ბაი ინდექსი',
    titleRu: 'Исани от Индекс',
    descriptionEn: 'Affordable apartments in Isani on Beri Gabriel Salosi Avenue.',
    descriptionKa: 'ხელმისაწვდომი აპარტამენტები ისანში.',
    descriptionRu: 'Доступные апартаменты в Исани.',
    developerSlug: 'index-wealth-management',
    locationCity: 'Tbilisi',
    locationArea: 'Isani',
    locationAddress: 'Beri Gabriel Salosi Ave',
    price: 49750,
    pricePerSqm: 995,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2027,
    featured: false,
  },
  {
    slug: 'dighomi-by-index',
    titleEn: 'Dighomi by Index',
    titleKa: 'დიღომი ბაი ინდექსი',
    titleRu: 'Дигоми от Индекс',
    descriptionEn: 'Completed residential complex in Saburtalo.',
    descriptionKa: 'დასრულებული საცხოვრებელი კომპლექსი საბურთალოში.',
    descriptionRu: 'Завершенный жилой комплекс в Сабуртало.',
    developerSlug: 'index-wealth-management',
    locationCity: 'Tbilisi',
    locationArea: 'Saburtalo',
    locationAddress: 'Christian Steven St, 24',
    price: 50000,
    pricePerSqm: 1000,
    propertyType: 'apartment',
    status: 'ready',
    deliveryYear: 2025,
    featured: false,
  },

  // ========================================
  // X2 DEVELOPMENT - 5 Projects
  // ========================================
  {
    slug: 'bakuriani-4rest',
    titleEn: 'Bakuriani 4Rest',
    titleKa: 'ბაკურიანი 4რესტ',
    titleRu: 'Бакуриани 4Рест',
    descriptionEn: 'Mountain resort apartments in Bakuriani.',
    descriptionKa: 'მთის კურორტის აპარტამენტები ბაკურიანში.',
    descriptionRu: 'Горнолыжные апартаменты в Бакуриани.',
    developerSlug: 'x2-development',
    locationCity: 'Bakuriani',
    locationAddress: 'Koba Tsakadze St, 32',
    price: 40000,
    pricePerSqm: 800,
    propertyType: 'apartment',
    status: 'ready',
    deliveryYear: 2022,
    featured: false,
  },
  {
    slug: 'dighomi-residence-x2',
    titleEn: 'Dighomi Residence',
    titleKa: 'დიღომის რეზიდენცია',
    titleRu: 'Дигоми Резиденс',
    descriptionEn: 'Residential complex in Didube on Nodar Bokhua Street.',
    descriptionKa: 'საცხოვრებელი კომპლექსი დიდუბეში.',
    descriptionRu: 'Жилой комплекс в Дидубе.',
    developerSlug: 'x2-development',
    locationCity: 'Tbilisi',
    locationArea: 'Didube',
    locationAddress: 'Nodar Bokhua St, 10',
    price: 67500,
    pricePerSqm: 1350,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2025,
    featured: false,
  },
  {
    slug: 'kazbegi-residence-x2',
    titleEn: 'Kazbegi Residence',
    titleKa: 'ყაზბეგის რეზიდენცია',
    titleRu: 'Казбеги Резиденс',
    descriptionEn: 'Residential development in Vake on Alexander Kazbegi Avenue.',
    descriptionKa: 'საცხოვრებელი განვითარება ვაკეში.',
    descriptionRu: 'Жилой комплекс в Ваке.',
    developerSlug: 'x2-development',
    locationCity: 'Tbilisi',
    locationArea: 'Vake',
    locationAddress: 'Alexander Kazbegi Ave, 34',
    price: 75000,
    pricePerSqm: 1500,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryYear: 2027,
    featured: false,
  },
  {
    slug: 'riverfront-residence-x2',
    titleEn: 'RiverFront Residence',
    titleKa: 'რივერფრონტ რეზიდენცია',
    titleRu: 'Риверфронт Резиденс',
    descriptionEn: 'Riverside residential complex in Didube.',
    descriptionKa: 'მდინარის პირას საცხოვრებელი კომპლექსი დიდუბეში.',
    descriptionRu: 'Жилой комплекс у реки в Дидубе.',
    developerSlug: 'x2-development',
    locationCity: 'Tbilisi',
    locationArea: 'Didube',
    locationAddress: 'Nodar Khosharauli St, 29',
    price: 58500,
    pricePerSqm: 1170,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2027,
    featured: false,
  },
  {
    slug: 'zenx-dighomi',
    titleEn: 'ZenX Dighomi',
    titleKa: 'ზენიქსი დიღომი',
    titleRu: 'ЗенИкс Дигоми',
    descriptionEn: 'Modern zen-inspired residential complex in Saburtalo.',
    descriptionKa: 'თანამედროვე ზენ-ინსპირირებული კომპლექსი საბურთალოში.',
    descriptionRu: 'Современный жилой комплекс в дзен-стиле.',
    developerSlug: 'x2-development',
    locationCity: 'Tbilisi',
    locationArea: 'Saburtalo',
    locationAddress: 'Petre Iberi St, 6a',
    price: 47500,
    pricePerSqm: 950,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q3',
    deliveryYear: 2027,
    featured: false,
  },

  // ========================================
  // APART DEVELOPMENT - 5 Projects
  // ========================================
  {
    slug: 'old-city-panorama',
    titleEn: 'Old City Panorama',
    titleKa: 'ძველი ქალაქის პანორამა',
    titleRu: 'Панорама Старого Города',
    descriptionEn: 'Residential complex in Chugureti with Old City views.',
    descriptionKa: 'საცხოვრებელი კომპლექსი ჭუღურეთში ძველი ქალაქის ხედით.',
    descriptionRu: 'Жилой комплекс в Чугурети с видом на Старый город.',
    developerSlug: 'apart-development',
    locationCity: 'Tbilisi',
    locationArea: 'Chugureti',
    locationAddress: 'Mikheil Bukhaidze St, 44g',
    price: 77500,
    pricePerSqm: 1550,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q1',
    deliveryYear: 2026,
    featured: false,
  },
  {
    slug: 'ezo-apart',
    titleEn: 'Ezo',
    titleKa: 'ეზო',
    titleRu: 'Эзо',
    descriptionEn: 'Urban residential project in Chugureti on Vedzatkhevi Street.',
    descriptionKa: 'ურბანული საცხოვრებელი პროექტი ჭუღურეთში.',
    descriptionRu: 'Городской жилой проект в Чугурети.',
    developerSlug: 'apart-development',
    locationCity: 'Tbilisi',
    locationArea: 'Chugureti',
    locationAddress: 'Vedzatkhevi St, 20',
    price: 75000,
    pricePerSqm: 1500,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2026,
    featured: false,
  },
  {
    slug: 'krtsanisi-margaliti',
    titleEn: 'Krtsanisi Margaliti',
    titleKa: 'კრწანისის მარგალიტი',
    titleRu: 'Крцаниси Маргалити',
    descriptionEn: 'Residential complex in Krtsanisi 1st Dead-end.',
    descriptionKa: 'საცხოვრებელი კომპლექსი კრწანისში.',
    descriptionRu: 'Жилой комплекс в Крцаниси.',
    developerSlug: 'apart-development',
    locationCity: 'Tbilisi',
    locationArea: 'Krtsanisi',
    locationAddress: 'Krtsanisi 1st Dead-end',
    price: 65000,
    pricePerSqm: 1300,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2027,
    featured: false,
  },
  {
    slug: 'alphecca-batumi',
    titleEn: 'Alphecca Batumi',
    titleKa: 'ალფექა ბათუმი',
    titleRu: 'Альфекка Батуми',
    descriptionEn: 'Premium residential complex in Batumi on Tamar Mepe Avenue.',
    descriptionKa: 'პრემიუმ საცხოვრებელი კომპლექსი ბათუმში.',
    descriptionRu: 'Премиум жилой комплекс в Батуми.',
    developerSlug: 'apart-development',
    locationCity: 'Batumi',
    locationAddress: 'Tamar Mepe Avenue, 1',
    price: 100000,
    pricePerSqm: 2000,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2028,
    featured: false,
  },
  {
    slug: 'lisi-lakers',
    titleEn: 'Lisi Lakers',
    titleKa: 'ლისის ლეიქერსი',
    titleRu: 'Лиси Лейкерс',
    descriptionEn: 'Lakeside residential complex in Vake on Amberki Tabidze Street.',
    descriptionKa: 'ტბის პირას საცხოვრებელი კომპლექსი ვაკეში.',
    descriptionRu: 'Жилой комплекс у озера в Ваке.',
    developerSlug: 'apart-development',
    locationCity: 'Tbilisi',
    locationArea: 'Vake',
    locationAddress: 'Amberki Tabidze St',
    price: 70000,
    pricePerSqm: 1400,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q3',
    deliveryYear: 2028,
    featured: false,
  },

  // ========================================
  // METROPOL - 5 Projects
  // ========================================
  {
    slug: 'metropol-oval',
    titleEn: 'Oval',
    titleKa: 'ოვალი',
    titleRu: 'Овал',
    descriptionEn: 'Uniquely designed oval-shaped residential complex in Batumi.',
    descriptionKa: 'უნიკალურად დიზაინებული ოვალური ფორმის კომპლექსი ბათუმში.',
    descriptionRu: 'Уникальный овальный жилой комплекс в Батуми.',
    developerSlug: 'metropol',
    locationCity: 'Batumi',
    price: 115500,
    pricePerSqm: 2310,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2027,
    featured: true,
  },
  {
    slug: 'metropol-cube',
    titleEn: 'Cube',
    titleKa: 'კუბი',
    titleRu: 'Куб',
    descriptionEn: 'Modern cube-inspired architecture in Batumi.',
    descriptionKa: 'თანამედროვე კუბური არქიტექტურა ბათუმში.',
    descriptionRu: 'Современная кубическая архитектура в Батуми.',
    developerSlug: 'metropol',
    locationCity: 'Batumi',
    price: 131750,
    pricePerSqm: 2635,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2027,
    featured: false,
  },
  {
    slug: 'the-parallel',
    titleEn: 'The Parallel',
    titleKa: 'პარალელი',
    titleRu: 'Параллель',
    descriptionEn: 'Coastal residential complex in Batumi with parallel block design.',
    descriptionKa: 'სანაპირო საცხოვრებელი კომპლექსი ბათუმში.',
    descriptionRu: 'Прибрежный жилой комплекс в Батуми.',
    developerSlug: 'metropol',
    locationCity: 'Batumi',
    price: 82050,
    pricePerSqm: 1641,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2027,
    featured: false,
  },
  {
    slug: 'metropol-ortachala',
    titleEn: 'Metropol Ortachala',
    titleKa: 'მეტროპოლ ორთაჭალა',
    titleRu: 'Метрополь Орта-Чала',
    descriptionEn: 'Multifunctional residential complex in Krtsanisi district.',
    descriptionKa: 'მრავალფუნქციური საცხოვრებელი კომპლექსი კრწანისში.',
    descriptionRu: 'Многофункциональный жилой комплекс в Крцаниси.',
    developerSlug: 'metropol',
    locationCity: 'Tbilisi',
    locationArea: 'Krtsanisi',
    price: 76700,
    pricePerSqm: 1534,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2027,
    featured: false,
  },
  {
    slug: 'metropol-kavtaradze',
    titleEn: 'Metropol Kavtaradze',
    titleKa: 'მეტროპოლ ქავთარაძე',
    titleRu: 'Метрополь Кавтарадзе',
    descriptionEn: 'Premium residential complex in prestigious Vake district.',
    descriptionKa: 'პრემიუმ საცხოვრებელი კომპლექსი პრესტიჟულ ვაკეში.',
    descriptionRu: 'Премиум жилой комплекс в престижном Ваке.',
    developerSlug: 'metropol',
    locationCity: 'Tbilisi',
    locationArea: 'Vake',
    price: 87000,
    pricePerSqm: 1740,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q2',
    deliveryYear: 2027,
    featured: true,
  },

  // ========================================
  // ALLIANCE GROUP - 4 Projects
  // ========================================
  {
    slug: 'alliance-centropolis',
    titleEn: 'Alliance Centropolis',
    titleKa: 'ალიანსი ცენტროპოლისი',
    titleRu: 'Альянс Центрополис',
    descriptionEn: 'Premium residential complex in Batumi Rustaveli area.',
    descriptionKa: 'პრემიუმ საცხოვრებელი კომპლექსი ბათუმის რუსთაველზე.',
    descriptionRu: 'Премиум жилой комплекс в районе Руставели.',
    developerSlug: 'alliance-group',
    locationCity: 'Batumi',
    locationArea: 'Rustaveli',
    price: 120000,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2028,
    featured: false,
  },
  {
    slug: 'alliance-renaissance',
    titleEn: 'Alliance Renaissance',
    titleKa: 'ალიანსი რენესანსი',
    titleRu: 'Альянс Ренессанс',
    descriptionEn: 'Coastal residential complex in Kobuleti.',
    descriptionKa: 'სანაპირო საცხოვრებელი კომპლექსი ქობულეთში.',
    descriptionRu: 'Прибрежный жилой комплекс в Кобулети.',
    developerSlug: 'alliance-group',
    locationCity: 'Kobuleti',
    price: 90000,
    pricePerSqm: 1800,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2028,
    featured: false,
  },
  {
    slug: 'alliance-highline',
    titleEn: 'Alliance Highline',
    titleKa: 'ალიანსი ჰაილაინი',
    titleRu: 'Альянс Хайлайн',
    descriptionEn: 'Premium high-end residential complex in Vake.',
    descriptionKa: 'პრემიუმ მაღალი კლასის საცხოვრებელი კომპლექსი ვაკეში.',
    descriptionRu: 'Премиум высококлассный жилой комплекс в Ваке.',
    developerSlug: 'alliance-group',
    locationCity: 'Tbilisi',
    locationArea: 'Vake',
    price: 150000,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2026,
    featured: false,
  },
  {
    slug: 'highlands-by-alliance',
    titleEn: 'Highlands by Alliance',
    titleKa: 'ჰაილენდსი ბაი ალიანსი',
    titleRu: 'Хайлэндс от Альянс',
    descriptionEn: 'Premium investment opportunity in Batumi. Highland-style residential complex.',
    descriptionKa: 'პრემიუმ საინვესტიციო შესაძლებლობა ბათუმში.',
    descriptionRu: 'Премиум инвестиционная возможность в Батуми.',
    developerSlug: 'alliance-group',
    locationCity: 'Batumi',
    price: 105000,
    pricePerSqm: 2100,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2025,
    featured: true,
  },

  // ========================================
  // GUMBATI GROUP - 5 Projects
  // ========================================
  {
    slug: 'portline-by-gumbati',
    titleEn: 'Portline by Gumbati',
    titleKa: 'პორტლაინი გუმბათი',
    titleRu: 'Портлайн от Гумбати',
    descriptionEn: 'Premium coastal residential complex in Batumi. Market leader with 500,000+ m² experience.',
    descriptionKa: 'პრემიუმ სანაპირო საცხოვრებელი კომპლექსი ბათუმში.',
    descriptionRu: 'Премиум прибрежный жилой комплекс в Батуми.',
    developerSlug: 'gumbati-group',
    locationCity: 'Batumi',
    locationAddress: 'Makatsaria St, 11',
    price: 128656,
    pricePerSqm: 2600,
    priceFrom: 128656,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q3',
    deliveryYear: 2026,
    featured: true,
  },
  {
    slug: 'midtown-batumi',
    titleEn: 'Midtown',
    titleKa: 'მიდთაუნი',
    titleRu: 'Мидтаун',
    descriptionEn: 'Centrally located residential complex in Batumi on Vakhtang Gorgasali Street.',
    descriptionKa: 'ცენტრალურად მდებარე საცხოვრებელი კომპლექსი ბათუმში.',
    descriptionRu: 'Центрально расположенный жилой комплекс в Батуми.',
    developerSlug: 'gumbati-group',
    locationCity: 'Batumi',
    locationAddress: 'Vakhtang Gorgasali St, 99',
    price: 136800,
    pricePerSqm: 1800,
    priceFrom: 136800,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2025,
    featured: false,
  },
  {
    slug: 'montemar-gonio',
    titleEn: 'Montemar',
    titleKa: 'მონტემარი',
    titleRu: 'Монтемар',
    descriptionEn: 'Coastal residential complex in Gonio on Andria Pirveltsodebuli Highway.',
    descriptionKa: 'სანაპირო საცხოვრებელი კომპლექსი გონიოში.',
    descriptionRu: 'Прибрежный жилой комплекс в Гонио.',
    developerSlug: 'gumbati-group',
    locationCity: 'Gonio',
    locationAddress: 'Andria Pirveltsodebuli Hwy 87g',
    price: 76516,
    pricePerSqm: 2035,
    priceFrom: 76516,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2028,
    featured: false,
  },
  {
    slug: 'boulevard-point-batumi',
    titleEn: 'Boulevard Point',
    titleKa: 'ბულვარ პოინთი',
    titleRu: 'Бульвар Поинт',
    descriptionEn: 'Ready residential complex in Batumi on Zghvispiri Street. Move-in ready.',
    descriptionKa: 'მზად საცხოვრებელი კომპლექსი ბათუმში.',
    descriptionRu: 'Готовый жилой комплекс в Батуми.',
    developerSlug: 'gumbati-group',
    locationCity: 'Batumi',
    locationAddress: 'Zghvispiri St, 1b',
    price: 69758,
    pricePerSqm: 2350,
    priceFrom: 69758,
    propertyType: 'apartment',
    status: 'ready',
    deliveryYear: 2024,
    featured: false,
  },
  {
    slug: 'subtropic-city',
    titleEn: 'Subtropic City',
    titleKa: 'სუბტროპიკ სითი',
    titleRu: 'Субтропик Сити',
    descriptionEn: 'Ready residential complex in Batumi. Established property from 2016.',
    descriptionKa: 'მზად საცხოვრებელი კომპლექსი ბათუმში.',
    descriptionRu: 'Готовый жилой комплекс в Батуми.',
    developerSlug: 'gumbati-group',
    locationCity: 'Batumi',
    locationAddress: 'Sherif Khimshiashvili St, 1',
    price: 91350,
    pricePerSqm: 2100,
    priceFrom: 91350,
    propertyType: 'apartment',
    status: 'ready',
    deliveryYear: 2016,
    featured: false,
  },

  // ========================================
  // ARCHI - 8 Featured Projects (largest developer)
  // ========================================
  {
    slug: 'archi-lilac',
    titleEn: 'Archi Lilac',
    titleKa: 'არჩი ლილაკი',
    titleRu: 'Арчи Лилак',
    descriptionEn: 'Modern residential complex in Gldani by Georgia\'s largest developer.',
    descriptionKa: 'თანამედროვე საცხოვრებელი კომპლექსი გლდანში.',
    descriptionRu: 'Современный жилой комплекс в Глдани.',
    developerSlug: 'archi',
    locationCity: 'Tbilisi',
    locationArea: 'Gldani',
    price: 70000,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2025,
    featured: false,
  },
  {
    slug: 'archi-varketili',
    titleEn: 'Archi Varketili',
    titleKa: 'არჩი ვარკეთილი',
    titleRu: 'Арчи Варкетили',
    descriptionEn: 'Affordable residential complex in Samgori district.',
    descriptionKa: 'ხელმისაწვდომი საცხოვრებელი კომპლექსი სამგორში.',
    descriptionRu: 'Доступный жилой комплекс в Самгори.',
    developerSlug: 'archi',
    locationCity: 'Tbilisi',
    locationArea: 'Samgori',
    price: 65000,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2025,
    featured: false,
  },
  {
    slug: 'archi-guramishvili',
    titleEn: 'Archi Guramishvili',
    titleKa: 'არჩი გურამიშვილი',
    titleRu: 'Арчи Гурамишвили',
    descriptionEn: 'Residential development in Nadzaladevi district.',
    descriptionKa: 'საცხოვრებელი განვითარება ნაძალადევში.',
    descriptionRu: 'Жилой комплекс в Надзаладеви.',
    developerSlug: 'archi',
    locationCity: 'Tbilisi',
    locationArea: 'Nadzaladevi',
    price: 68000,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2026,
    featured: false,
  },
  {
    slug: 'archi-kikvidze-garden',
    titleEn: 'Archi Kikvidze Garden',
    titleKa: 'არჩი ქიქვიძის ბაღი',
    titleRu: 'Арчи Киквидзе Гарден',
    descriptionEn: 'Garden-style residential complex in Nadzaladevi.',
    descriptionKa: 'ბაღის სტილის საცხოვრებელი კომპლექსი ნაძალადევში.',
    descriptionRu: 'Жилой комплекс в садовом стиле.',
    developerSlug: 'archi',
    locationCity: 'Tbilisi',
    locationArea: 'Nadzaladevi',
    price: 72000,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2027,
    featured: false,
  },
  {
    slug: 'archi-isani',
    titleEn: 'Archi Isani',
    titleKa: 'არჩი ისანი',
    titleRu: 'Арчи Исани',
    descriptionEn: 'Completed residential complex in Isani. Ready for occupancy.',
    descriptionKa: 'დასრულებული საცხოვრებელი კომპლექსი ისანში.',
    descriptionRu: 'Завершенный жилой комплекс в Исани.',
    developerSlug: 'archi',
    locationCity: 'Tbilisi',
    locationArea: 'Isani',
    price: 75000,
    pricePerSqm: 1500,
    propertyType: 'apartment',
    status: 'ready',
    deliveryYear: 2024,
    featured: false,
  },
  {
    slug: 'archi-kokhta-bakuriani',
    titleEn: 'Archi Kokhta',
    titleKa: 'არჩი კოხტა',
    titleRu: 'Арчи Кохта',
    descriptionEn: 'Mountain resort apartments in Bakuriani. Completed ski resort.',
    descriptionKa: 'მთის კურორტის აპარტამენტები ბაკურიანში.',
    descriptionRu: 'Горнолыжные апартаменты в Бакуриани.',
    developerSlug: 'archi',
    locationCity: 'Bakuriani',
    price: 50000,
    propertyType: 'apartment',
    status: 'ready',
    deliveryYear: 2022,
    featured: false,
  },
  {
    slug: 'archi-rustavi',
    titleEn: 'Archi Rustavi',
    titleKa: 'არჩი რუსთავი',
    titleRu: 'Арчи Рустави',
    descriptionEn: 'Residential development in Rustavi city.',
    descriptionKa: 'საცხოვრებელი განვითარება რუსთავში.',
    descriptionRu: 'Жилой комплекс в Рустави.',
    developerSlug: 'archi',
    locationCity: 'Rustavi',
    price: 60000,
    propertyType: 'apartment',
    status: 'underConstruction',
    featured: false,
  },
  {
    slug: 'archi-akhmeteli',
    titleEn: 'Archi Akhmeteli',
    titleKa: 'არჩი ახმეტელი',
    titleRu: 'Арчи Ахметели',
    descriptionEn: 'Modern residential complex in Gldani district.',
    descriptionKa: 'თანამედროვე საცხოვრებელი კომპლექსი გლდანში.',
    descriptionRu: 'Современный жилой комплекс в Глдани.',
    developerSlug: 'archi',
    locationCity: 'Tbilisi',
    locationArea: 'Gldani',
    price: 69000,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2026,
    featured: false,
  },

  // ========================================
  // ELT BUILDING - 5 Projects
  // ========================================
  {
    slug: 'compact-house-batumi',
    titleEn: 'Compact House',
    titleKa: 'კომპაქტ ჰაუსი',
    titleRu: 'Компакт Хаус',
    descriptionEn: 'Budget-friendly compact apartments in Batumi on Rurua Street.',
    descriptionKa: 'ბიუჯეტური კომპაქტური აპარტამენტები ბათუმში.',
    descriptionRu: 'Бюджетные компактные апартаменты в Батуми.',
    developerSlug: 'elt-building',
    locationCity: 'Batumi',
    locationAddress: 'Rurua St, 10',
    price: 40000,
    pricePerSqm: 800,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q1',
    deliveryYear: 2026,
    featured: false,
  },
  {
    slug: 'barcelo-tbilisi',
    titleEn: 'Barcelo Tbilisi',
    titleKa: 'ბარსელო თბილისი',
    titleRu: 'Барсело Тбилиси',
    descriptionEn: 'Branded hotel residence in Tbilisi. International Barcelo Hotels brand.',
    descriptionKa: 'ბრენდირებული სასტუმრო რეზიდენცია თბილისში.',
    descriptionRu: 'Брендированная отельная резиденция в Тбилиси.',
    developerSlug: 'elt-building',
    locationCity: 'Tbilisi',
    locationAddress: 'Richard Holbrooke St, 12',
    price: 150000,
    propertyType: 'aparthotel',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2027,
    featured: true,
  },
  {
    slug: 'status-house-batumi',
    titleEn: 'Status House',
    titleKa: 'სტატუს ჰაუსი',
    titleRu: 'Статус Хаус',
    descriptionEn: 'Modern residential complex in Batumi on Adlia Street.',
    descriptionKa: 'თანამედროვე საცხოვრებელი კომპლექსი ბათუმში.',
    descriptionRu: 'Современный жилой комплекс в Батуми.',
    developerSlug: 'elt-building',
    locationCity: 'Batumi',
    locationAddress: 'Adlia St',
    price: 60000,
    pricePerSqm: 1200,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2027,
    featured: false,
  },
  {
    slug: 'marina-club-batumi',
    titleEn: 'Marina Club',
    titleKa: 'მარინა კლუბი',
    titleRu: 'Марина Клуб',
    descriptionEn: 'Marina-style residential complex in Batumi.',
    descriptionKa: 'მარინას სტილის საცხოვრებელი კომპლექსი ბათუმში.',
    descriptionRu: 'Жилой комплекс в стиле марины в Батуми.',
    developerSlug: 'elt-building',
    locationCity: 'Batumi',
    locationAddress: 'Lech and Maria Kachinski St, 17',
    price: 75000,
    pricePerSqm: 1500,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q2',
    deliveryYear: 2026,
    featured: false,
  },
  {
    slug: 'optima-residence-batumi',
    titleEn: 'Optima Residence',
    titleKa: 'ოპტიმა რეზიდენსი',
    titleRu: 'Оптима Резиденс',
    descriptionEn: 'Optimized residential complex in Batumi on Adlia Street.',
    descriptionKa: 'ოპტიმიზირებული საცხოვრებელი კომპლექსი ბათუმში.',
    descriptionRu: 'Оптимизированный жилой комплекс в Батуми.',
    developerSlug: 'elt-building',
    locationCity: 'Batumi',
    locationAddress: 'Adlia Street, 14',
    price: 60000,
    pricePerSqm: 1200,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2025,
    featured: false,
  },

  // ========================================
  // DOMUS DEVELOPMENT - 6 Projects
  // ========================================
  {
    slug: 'domus-chavchavadze-31',
    titleEn: 'Domus Chavchavadze 31',
    titleKa: 'დომუსი ჭავჭავაძე 31',
    titleRu: 'Домус Чавчавадзе 31',
    descriptionEn: 'Ultra-premium residential complex in the heart of Vake.',
    descriptionKa: 'ულტრა-პრემიუმ საცხოვრებელი კომპლექსი ვაკის გულში.',
    descriptionRu: 'Ультра-премиум жилой комплекс в сердце Ваке.',
    developerSlug: 'domus-development',
    locationCity: 'Tbilisi',
    locationArea: 'Vake',
    price: 160000,
    pricePerSqm: 3200,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2026,
    featured: true,
  },
  {
    slug: 'domus-avlabari',
    titleEn: 'Domus Avlabari',
    titleKa: 'დომუსი ავლაბარი',
    titleRu: 'Домус Авлабари',
    descriptionEn: 'Premium residential complex in Isani district.',
    descriptionKa: 'პრემიუმ საცხოვრებელი კომპლექსი ისანში.',
    descriptionRu: 'Премиум жилой комплекс в Исани.',
    developerSlug: 'domus-development',
    locationCity: 'Tbilisi',
    locationArea: 'Isani',
    price: 90000,
    pricePerSqm: 1800,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q2',
    deliveryYear: 2028,
    featured: false,
  },
  {
    slug: 'domusi-gazapkhuli',
    titleEn: 'Domusi Gazapkhuli',
    titleKa: 'დომუსი გაზაფხული',
    titleRu: 'Домуси Газапхули',
    descriptionEn: 'Premium spring-inspired residential complex in Vake.',
    descriptionKa: 'პრემიუმ გაზაფხულ-ინსპირირებული კომპლექსი ვაკეში.',
    descriptionRu: 'Премиум жилой комплекс весенней тематики.',
    developerSlug: 'domus-development',
    locationCity: 'Tbilisi',
    locationArea: 'Vake',
    price: 87500,
    pricePerSqm: 1750,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2026,
    featured: false,
  },
  {
    slug: 'domus-nea',
    titleEn: 'Domus Nea',
    titleKa: 'დომუსი ნეა',
    titleRu: 'Домус Неа',
    descriptionEn: 'Contemporary residential complex in prestigious Vake.',
    descriptionKa: 'თანამედროვე საცხოვრებელი კომპლექსი პრესტიჟულ ვაკეში.',
    descriptionRu: 'Современный жилой комплекс в престижном Ваке.',
    developerSlug: 'domus-development',
    locationCity: 'Tbilisi',
    locationArea: 'Vake',
    price: 95000,
    pricePerSqm: 1900,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q2',
    deliveryYear: 2028,
    featured: false,
  },
  {
    slug: 'domus-sera',
    titleEn: 'Domus Sera',
    titleKa: 'დომუსი სერა',
    titleRu: 'Домус Сера',
    descriptionEn: 'Ultra-premium residential complex in Vake. Highest-end offering at $4,000/m².',
    descriptionKa: 'ულტრა-პრემიუმ საცხოვრებელი კომპლექსი ვაკეში.',
    descriptionRu: 'Ультра-премиум жилой комплекс в Ваке.',
    developerSlug: 'domus-development',
    locationCity: 'Tbilisi',
    locationArea: 'Vake',
    price: 200000,
    pricePerSqm: 4000,
    propertyType: 'apartment',
    status: 'underConstruction',
    featured: true,
  },
  {
    slug: 'domus-kvariati',
    titleEn: 'Domus Kvariati',
    titleKa: 'დომუსი კვარიათი',
    titleRu: 'Домус Квариати',
    descriptionEn: 'Upcoming coastal residential project in Kvariati.',
    descriptionKa: 'მომავალი სანაპირო საცხოვრებელი პროექტი კვარიათში.',
    descriptionRu: 'Предстоящий прибрежный жилой проект в Квариати.',
    developerSlug: 'domus-development',
    locationCity: 'Kvariati',
    price: 110000,
    propertyType: 'apartment',
    status: 'offPlan',
    featured: false,
  },

  // ========================================
  // ANAGI DEVELOPMENT - 5 Projects
  // ========================================
  {
    slug: 'park-home-saburtalo',
    titleEn: 'Park Home Saburtalo',
    titleKa: 'პარკ ჰომ საბურთალო',
    titleRu: 'Парк Хоум Сабуртало',
    descriptionEn: 'Park-adjacent residential complex in Vake on Gazapkhulis Street.',
    descriptionKa: 'პარკთან მდებარე საცხოვრებელი კომპლექსი ვაკეში.',
    descriptionRu: 'Жилой комплекс рядом с парком в Ваке.',
    developerSlug: 'anagi-development',
    locationCity: 'Tbilisi',
    locationArea: 'Vake',
    locationAddress: 'Gazapkhulis St, 4',
    price: 92500,
    pricePerSqm: 1850,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2024,
    featured: false,
  },
  {
    slug: 'city-home-avlabari',
    titleEn: 'City Home Avlabari',
    titleKa: 'სითი ჰომ ავლაბარი',
    titleRu: 'Сити Хоум Авлабари',
    descriptionEn: 'Urban residential complex in Isani on Bochorma Street.',
    descriptionKa: 'ურბანული საცხოვრებელი კომპლექსი ისანში.',
    descriptionRu: 'Городской жилой комплекс в Исани.',
    developerSlug: 'anagi-development',
    locationCity: 'Tbilisi',
    locationArea: 'Isani',
    locationAddress: 'Bochorma St, 27',
    price: 95000,
    pricePerSqm: 1900,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2025,
    featured: false,
  },
  {
    slug: 'city-home-kipshidze',
    titleEn: 'City Home Kipshidze',
    titleKa: 'სითი ჰომ ყიფშიძე',
    titleRu: 'Сити Хоум Кипшидзе',
    descriptionEn: 'Modern city apartments in Vake on Nikoloz Qipshidze Street.',
    descriptionKa: 'თანამედროვე ქალაქის აპარტამენტები ვაკეში.',
    descriptionRu: 'Современные городские апартаменты в Ваке.',
    developerSlug: 'anagi-development',
    locationCity: 'Tbilisi',
    locationArea: 'Vake',
    locationAddress: 'Nikoloz Qipshidze St, 20a',
    price: 105000,
    pricePerSqm: 2100,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2025,
    featured: false,
  },
  {
    slug: 'green-cape-botanico',
    titleEn: 'Green Cape Botanico',
    titleKa: 'გრინ კეიპ ბოტანიკო',
    titleRu: 'Грин Кейп Ботанико',
    descriptionEn: 'Botanical-themed residential complex in Batumi.',
    descriptionKa: 'ბოტანიკური თემატიკის საცხოვრებელი კომპლექსი ბათუმში.',
    descriptionRu: 'Жилой комплекс ботанической тематики в Батуми.',
    developerSlug: 'anagi-development',
    locationCity: 'Batumi',
    locationAddress: 'Baghi 1st Dead End, 3/21',
    price: 125000,
    pricePerSqm: 2500,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q3',
    deliveryYear: 2023,
    featured: false,
  },
  {
    slug: 'villa-ambassadori',
    titleEn: 'Villa Ambassadori',
    titleKa: 'ვილა ამბასადორი',
    titleRu: 'Вилла Амбассадори',
    descriptionEn: 'Exclusive villa development in Kachreti, Tbilisi.',
    descriptionKa: 'ექსკლუზიური ვილების განვითარება კახრეთში.',
    descriptionRu: 'Эксклюзивная застройка вилл в Кахрети.',
    developerSlug: 'anagi-development',
    locationCity: 'Tbilisi',
    locationArea: 'Kachreti',
    locationAddress: 'Agmashenebeli St, 7',
    price: 85000,
    pricePerSqm: 1700,
    propertyType: 'villa',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2020,
    featured: false,
  },

  // ========================================
  // BLOX - 7 Projects
  // ========================================
  {
    slug: 'blox-krtsanisi',
    titleEn: 'Blox Krtsanisi',
    titleKa: 'ბლოქსი კრწანისი',
    titleRu: 'Блокс Крцаниси',
    descriptionEn: 'Modern residential complex in Krtsanisi district.',
    descriptionKa: 'თანამედროვე საცხოვრებელი კომპლექსი კრწანისში.',
    descriptionRu: 'Современный жилой комплекс в Крцаниси.',
    developerSlug: 'blox',
    locationCity: 'Tbilisi',
    locationArea: 'Krtsanisi',
    price: 95000,
    pricePerSqm: 1900,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q3',
    deliveryYear: 2023,
    featured: false,
  },
  {
    slug: 'blox-beliashvili-2',
    titleEn: 'Blox Beliashvili 2',
    titleKa: 'ბლოქსი ბელიაშვილი 2',
    titleRu: 'Блокс Белиашвили 2',
    descriptionEn: 'Affordable residential complex in Didube.',
    descriptionKa: 'ხელმისაწვდომი საცხოვრებელი კომპლექსი დიდუბეში.',
    descriptionRu: 'Доступный жилой комплекс в Дидубе.',
    developerSlug: 'blox',
    locationCity: 'Tbilisi',
    locationArea: 'Didube',
    price: 62500,
    pricePerSqm: 1250,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2026,
    featured: false,
  },
  {
    slug: 'blox-gudauri',
    titleEn: 'Blox Gudauri',
    titleKa: 'ბლოქსი გუდაური',
    titleRu: 'Блокс Гудаури',
    descriptionEn: 'Premium ski resort apartments in Gudauri mountain resort.',
    descriptionKa: 'პრემიუმ სათხილამურო კურორტის აპარტამენტები გუდაურში.',
    descriptionRu: 'Премиум апартаменты на горнолыжном курорте Гудаури.',
    developerSlug: 'blox',
    locationCity: 'Gudauri',
    price: 150000,
    pricePerSqm: 3000,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2027,
    featured: true,
  },
  {
    slug: 'blox-varketili',
    titleEn: 'Blox Varketili',
    titleKa: 'ბლოქსი ვარკეთილი',
    titleRu: 'Блокс Варкетили',
    descriptionEn: 'Residential complex in Samgori district.',
    descriptionKa: 'საცხოვრებელი კომპლექსი სამგორში.',
    descriptionRu: 'Жилой комплекс в Самгори.',
    developerSlug: 'blox',
    locationCity: 'Tbilisi',
    locationArea: 'Samgori',
    price: 60000,
    pricePerSqm: 1200,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q3',
    deliveryYear: 2025,
    featured: false,
  },
  {
    slug: 'blox-ortachala',
    titleEn: 'Blox Ortachala',
    titleKa: 'ბლოქსი ორთაჭალა',
    titleRu: 'Блокс Ортачала',
    descriptionEn: 'Modern residential development in Krtsanisi.',
    descriptionKa: 'თანამედროვე საცხოვრებელი განვითარება კრწანისში.',
    descriptionRu: 'Современный жилой комплекс в Крцаниси.',
    developerSlug: 'blox',
    locationCity: 'Tbilisi',
    locationArea: 'Krtsanisi',
    price: 70000,
    pricePerSqm: 1400,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q3',
    deliveryYear: 2028,
    featured: false,
  },
  {
    slug: 'blox-didi-dighomi',
    titleEn: 'Blox Didi Dighomi',
    titleKa: 'ბლოქსი დიდი დიღომი',
    titleRu: 'Блокс Диди Дигоми',
    descriptionEn: 'Budget-friendly apartments in Saburtalo.',
    descriptionKa: 'ბიუჯეტური აპარტამენტები საბურთალოში.',
    descriptionRu: 'Бюджетные апартаменты в Сабуртало.',
    developerSlug: 'blox',
    locationCity: 'Tbilisi',
    locationArea: 'Saburtalo',
    price: 52500,
    pricePerSqm: 1050,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q2',
    deliveryYear: 2026,
    featured: false,
  },
  {
    slug: 'blox-sarajishvili',
    titleEn: 'Blox Sarajishvili',
    titleKa: 'ბლოქსი საराჯიშვილი',
    titleRu: 'Блокс Сараджишвили',
    descriptionEn: 'Affordable residential complex in Gldani.',
    descriptionKa: 'ხელმისაწვდომი საცხოვრებელი კომპლექსი გლდანში.',
    descriptionRu: 'Доступный жилой комплекс в Глдани.',
    developerSlug: 'blox',
    locationCity: 'Tbilisi',
    locationArea: 'Gldani',
    price: 55000,
    pricePerSqm: 1100,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2028,
    featured: false,
  },

  // ========================================
  // PILLAR GROUP - 2 Projects
  // ========================================
  {
    slug: 'pillar-park-samgori',
    titleEn: 'Pillar Park Samgori',
    titleKa: 'პილარ პარკ სამგორი',
    titleRu: 'Пиллар Парк Самгори',
    descriptionEn: 'Residential park complex in Isani on Kakheti highway.',
    descriptionKa: 'საცხოვრებელი პარკის კომპლექსი ისანში.',
    descriptionRu: 'Жилой парковый комплекс в Исани.',
    developerSlug: 'pillar-group',
    locationCity: 'Tbilisi',
    locationArea: 'Isani',
    locationAddress: 'Kakheti highway 1a',
    price: 85000,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q3',
    deliveryYear: 2027,
    featured: false,
  },
  {
    slug: 'pillar-park-saburtalo',
    titleEn: 'Pillar Park',
    titleKa: 'პილარ პარკი',
    titleRu: 'Пиллар Парк',
    descriptionEn: 'Green residential complex in Saburtalo on Lasha Lashkhia Street.',
    descriptionKa: 'მწვანე საცხოვრებელი კომპლექსი საბურთალოში.',
    descriptionRu: 'Зеленый жилой комплекс в Сабуртало.',
    developerSlug: 'pillar-group',
    locationCity: 'Tbilisi',
    locationArea: 'Saburtalo',
    locationAddress: 'Lasha Lashkhia Street 10',
    price: 103014,
    pricePerSqm: 1400,
    priceFrom: 103014,
    propertyType: 'apartment',
    status: 'underConstruction',
    deliveryQuarter: 'Q4',
    deliveryYear: 2026,
    featured: false,
  },
]

async function main() {
  console.log('🚀 Starting complete real projects seed...\n')
  console.log(`📊 Total projects to create: ${projectsData.length}\n`)

  // Delete existing projects
  console.log('🗑️  Deleting existing projects...')
  await prisma.project.deleteMany()
  console.log('✅ Existing projects deleted\n')

  // Fetch all developers
  console.log('📋 Fetching developers...')
  const developers = await prisma.developer.findMany()
  const devMap = new Map(developers.map(d => [d.slug, d]))
  console.log(`✅ Found ${developers.length} developers\n`)

  console.log('👷 Creating projects...\n')

  let created = 0
  let skipped = 0

  for (const projectData of projectsData) {
    const developer = devMap.get(projectData.developerSlug)

    if (!developer) {
      console.log(`⚠️  Skipping ${projectData.titleEn} - developer '${projectData.developerSlug}' not found`)
      skipped++
      continue
    }

    try {
      await prisma.project.create({
        data: {
          slug: projectData.slug,
          titleEn: projectData.titleEn,
          titleKa: projectData.titleKa,
          titleRu: projectData.titleRu,
          descriptionEn: projectData.descriptionEn,
          descriptionKa: projectData.descriptionKa,
          descriptionRu: projectData.descriptionRu,
          developerId: developer.id,
          locationCity: projectData.locationCity,
          locationArea: projectData.locationArea,
          locationAddress: projectData.locationAddress,
          price: projectData.price,
          pricePerSqm: projectData.pricePerSqm,
          propertyType: projectData.propertyType,
          status: projectData.status,
          deliveryQuarter: projectData.deliveryQuarter,
          deliveryYear: projectData.deliveryYear,
          featured: projectData.featured,
          published: true,
        },
      })
      created++
      if (created % 10 === 0) {
        console.log(`   ... ${created} projects created`)
      }
    } catch (error) {
      console.error(`❌ Error creating ${projectData.titleEn}:`, error)
      skipped++
    }
  }

  console.log('\n' + '═'.repeat(70))
  console.log(`\n✅ Complete projects seed finished!`)
  console.log(`   - Created: ${created} projects`)
  console.log(`   - Skipped: ${skipped} projects`)
  console.log(`   - From ${developers.length} developers`)
  console.log(`   - Data Source: korter.ge\n`)
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
